* adz

It is a mini-wrapper CLI tool to run my Emacs development environment and others like graphic, web and IDE tools, and rsync into my NixOS machine. 

* Dependencies
- [[https://github.com/krei-systems/marie][Marie]] 

* Usage
We can build it using this command,
If there's no marie yet, 
#+begin_Src
make clone
#+end_Src
#+begin_src makefile
make build
#+end_src
To remove the executable
#+begin_Src
make clean
#+end_src

After building, an executable named adz will be created. You can run it from within the project directory using,
#+begin_src
./adz --help
#+end_src
* Test
To test it if it's working properly,
#+begin_Src
adz h
#+end_Src

To make it accessible globally, insert this into your shell configuration files—.bashrc or .zshenv,
#+begin_src lisp
export PATH="$HOME<your/project/directory/>:$PATH"
#+end_Src

* Lisp Flakes
For NixOS users and have their flakes inside their machine for development environment, you have to change the values in the special variable named [[https://github.com/eldriv/adz/blob/main/src/core.lisp][*path*]] in able to adjust it with your own pathname.
Then run,
#+begin_Src lisp
adz lf e # To run Emacs development environment
adz lf sv # To Check SBCL version
#+end_Src

*NOTE:* You can be able to extend this and change any values depends on your own needs, just see the source code in able to do that and if you have NixOS installed and might want to use flakes then 
this CLI codebase structure is beneficial for you.